server:
  port: 8888

spring:
  application:
    name: spring-config-server
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: operation
  cloud:
    config:
      server:
        bootstrap: false
        git:
          enabled: false
          uri: https://dev.azure.com/MY_ORG/DevopsConfig/_git/Config-Central-REPO
          skipSslValidation: true
          default-label: develop
          clone-on-start: true
          force-pull: true
          timeout: 10
          username: MY_USER
          password: MY_PAT
        default-application-name: application
        default-profile: default

config:
  providers:
    nexl:
      enabled: true
      base-url: http://nexl:8181
      order: 1
    git:
      enabled: true
      fallback: false
      order: 2

management:
  health:
    config:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    com.edx.spring.config.central.server: DEBUG
    org.springframework.cloud.config.server: INFO
    org.springframework.beans.factory.support: DEBUG
