
server:
  port: 8888

spring:
  application:
    name: spring-config-server
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: operation
  cloud:
    config:
      server:
        bootstrap: false
        git:
          enabled: true
          uri: https://dev.azure.com/MY_ORG/DevopsConfig/_git/Config-Central-REPO
          skipSslValidation: true
          default-label: develop          # branch to read from
          clone-on-start: true            # clone at startup
          force-pull: true                # always refresh remote
          timeout: 10
          username: MY_USER
          password: MY_PAT
          overrides:
            spring.cloud.config.server.git.order: 2  # Lower priority than Nexl
        # Disable default repository creation
        default-application-name: application
        default-profile: default


config:
  providers:
    nexl:
      enabled: true
      base-url: http://nexl:8181
      order: 1  # Higher priority
    git:
      enabled: true
      fallback: false  # Disable fallback to prevent interference
      order: 2  # Higher priority

# Disable health checks that might be causing conflicts
management:
  health:
    config:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 3600
  mvc:
    static-path-pattern: /**
    contentnegotiation:
      favor-parameter: false
      favor-path-extension: false
      media-types:
        css: text/css
        js: application/javascript
        woff: font/woff
        woff2: font/woff2
# Logging configuration
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com.edx.spring.config.central.server: DEBUG
    org.springframework.cloud.config.server: INFO