server:
  port: 8888

spring:
  application:
    name: spring-config-server
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: custom-repo
  cloud:
    config:
      server:
        git:
          enabled: false
        # Disable default repository creation
        default-application-name: application
        default-profile: default
        bootstrap: false

config:
  providers:
    nexl:
      enabled: true
      base-url: http://nexl:8181

# Disable health checks that might be causing conflicts
management:
  health:
    config:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info

# Enable debug logging to see what's happening
logging:
  level:
    org.springframework.cloud.config.server: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    com.edx.spring.config: DEBUG
