
server:
  port: 8888

spring:
  application:
    name: spring-config-server
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: operation
  cloud:
    config:
      server:
        git:
          enabled: false
        # Disable default repository creation
        default-application-name: application
        default-profile: default
        bootstrap: false

config:
  providers:
    nexl:
      enabled: true
      base-url: http://nexl:8181
    git:
      enabled: true
      fallback: false  # Disable fallback to prevent interference

# Disable health checks that might be causing conflicts
management:
  health:
    config:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 3600
  mvc:
    static-path-pattern: /**
    contentnegotiation:
      favor-parameter: false
      favor-path-extension: false
      media-types:
        css: text/css
        js: application/javascript
        woff: font/woff
        woff2: font/woff2
# Logging configuration
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com.edx.spring.config.central.server: DEBUG
    org.springframework.cloud.config.server: INFO