spring:
  application:
    name: spring-config-server
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: operation
  cloud:
    config:
      server:
        #        composite:
        #        enabled: false
        git:
          enabled: true
          uri: https://dev.azure.com/IDI-Insurance/DevopsConfig/_git/IDI-Apps-Config-Central
          skipSslValidation: true
          default-label: develop          # branch to read from
          clone-on-start: true            # clone at startup
          force-pull: true                # always refresh remote
          timeout: 10
          username: myuser
          password: MY_PAT
          overrides:
            spring.cloud.config.server.git.order: 2  # Lower priority than Nexl
        # Disable default repository creation
        default-application-name: application
        default-profile: default
        bootstrap: false


#
#config:
#  providers:
#    nexl:
#      enabled: true
#      base-url: http://nexl.relay.yashir.co.il:8181
#      order: 1  # Higher priority
#    git:
#      enabled: true
#      fallback: false  # Disable fallback to prevent interference
#      order: 2  # Higher priority

# Disable health checks that might be causing conflicts
management:
  health:
    config:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info
# Logging configuration
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com.edx.spring.config.central.server: DEBUG
    org.springframework.cloud.config.server: INFO
    org.springframework.cloud.config: DEBUG
    org.eclipse.jgit: DEBUG