@Library('shared-library@MicroServiceCD_upgrades') _

def config=["buildImage":"true",
			"msImageName":"config-central-server",
			"folderName":"config_central_server",
			"buildFolder":"SpringConfigCentral/config_central_server"]

MicroServiceCI21(config)
